#
# Makefile for Phoenix-RTOS stm32-multi
#
# Copyright 2022 Phoenix Systems
#

LOCAL_PATH := $(call my-dir)

NAME := libnrf91-multi
SRCS := $(wildcard $(LOCAL_PATH)*.c)
DEPS := libtty

include $(static-lib.mk)
